name: iOS starter workflow

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Default Scheme
        run: |
          zip -s 1.9g -r ./xcode.zip /Applications/Xcode.app/Contents
      
          
